from ScoreCalculationInterface.ScoreCalculationInterface import ScoreCalculationInterface
from ScoreCalculationInterface.MatchScoreCalculationInterface import MatchScoreCalculationInterface
from ScoreCalculationInterface.SetScoreCalculationInterface import SetScoreCalculationInterface
from ScoreCalculationInterface.GameScoreCalculationInterface import GameScoreCalculationInterface
